---
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
plugins:
- react
- react-native
extends:
- eslint-config-standard
- plugin:react/recommended
- plugin:react-native/all
rules:
  no-multi-spaces: 0
  object-property-newline: 0
  standard/object-curly-even-spacing: 0
  react/prop-types: 0
  promise/param-names: 0
  react/no-children-prop: 0
  react/display-name: 0
  react-native/no-color-literals: 0
env:
  node: true
  browser: true
  es6: true
