---
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
plugins:
- react
- react-native
extends:
- eslint-config-standard
- plugin:react/recommended
- plugin:react-native/all
rules:
  camelcase: 0
  react/prop-types: 0
  react/display-name: 0
env:
  node: true
  browser: true
  es6: true
