#!/usr/bin/bash

foreground="#fafafa"
background="#373b41"
font="a14"
bat="BAT0"
interval=15

clock () {
  echo -n `date "+%a %m-%d %H:%M"`
}

usedmem () {
  echo -n `free -m | awk '/Mem/ {print $3}'`
}

totalmem () {
  echo -n `free -m | awk '/Mem/ {print $2}'`
}

volume () {
  echo -n `amixer get Master | awk '/Mono/ {print $6=="[off]"?$6:$4}'`
}

battery () {
  cur=$(cat /sys/class/power_supply/$bat/energy_now)
  full=$(cat /sys/class/power_supply/$bat/energy_full)
  echo -n "$(($cur * 100 / $full))"
}

while true; do
  echo "%{c} [$(clock)]"\
    "- [$(usedmem)/$(totalmem)M]"\
    "- $(volume)"\
    "- [$(battery)%]"
  sleep $interval
done | lemonbar -p \
  -F $foreground \
  -B $background \
  -f $font
