#!/usr/bin/env sh

#
# wm independent hotkeys
#

# terminal emulator
super + Return
  urxvtc -e "tmux"

# program launcher
super + @space
  dmenu_run -fn 'Operator Mono:pixelsize=10:style=Book' \
    -nb '#373b41' -nf '#c5c8c6' -sf '#fafafa'

# make sxhkd reload its configuration files:
super + Escape
  pkill -USR1 -x sxhkd

# start a quake-like terminal
super + grave
  tdrop -a -x 5 -y 18 -w 1428 -h 875 -s dropdown urxvtc

## media keys
XF86AudioRaiseVolume
  amixer -q sset Master,0 5+ unmute

XF86AudioLowerVolume
  amixer -q sset Master,0 5- unmute

XF86AudioMute
  amixer -q set Master toggle

XF86TouchpadToggle
  ~/.bin/touchpadctl toggle

XF86MonBrightnessUp
  xbacklight -inc 5

XF86MonBrightnessDown
  xbacklight -dec 5

XF86KbdBrightnessUp
  xbacklight -inc 5

XF86KbdBrightnessDown
  xbacklight -dec 5

# grab screenshot of current desktop
super + shift + 3
  import -window root "/tmp/screenshot-$(date '+%Y%m%d-%H%M%S').png"

#
# bspwm hotkeys
#

# quit bspwm normally
super + alt + Escape
  bspc quit

# close and kill
super + {_,shift + }q
  bspc node -{c,k}

# alternate between the tiled and monocle layout
super + m
  bspc desktop -l next

super + y
  bspc query -N -n focused.automatic && bspc node -n last.!automatic || bspc node last.leaf -n focused

#
# state/flags
#

# set the window state
super + {t,shift + t,s,f}
  bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# alternate between the tiled and monocle layout
super + m
  bspc desktop -l next

# set the node flags
super + ctrl + {x,y,z}
  bspc node -g {locked,sticky,private}

#
# preselect
#

# preselect the direction
super + ctrl + {h,j,k,l}
  bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
  bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
  bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
  bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# focus/swap
#

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
  bspc node -{f,s} {west,south,north,east}

# focus the last node
super + {Tab}
  bspc {node} -f last

# focus the older or newer node in the focus history
super + {o,i}
  bspc wm -h off; \
  bspc node {older,newer} -f; \
  bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
  bspc {desktop -f,node -d} '^{1-9,10}'

#
# move/resize
#

# expand a window by moving one of its side outward
super + alt + {h,j,k,l}
  bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {h,j,k,l}
  bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
  bspc node -v {-20 0,0 20,0 -20,20 0}

