#!/bin/bash

# Usage:
# color day
# color night 40

if [[ "$1" == "day" ]]; then
  xcalib -clear && \
  xcalib ~/.config/color-profiles/Color\ LCD-77E200AD-B0E6-0317-4BBF-F8B53DA3952C.icc
elif [[ "$1" == "night" ]]; then
  FILTER=$2
  xcalib -clear && \
  xcalib -green 1 1 $((100 - ( 100 - $FILTER ) / 2 )) -blue 1 1 $FILTER -alter
fi
