#!/bin/bash

echo "`
    curl    -sS "https://dict.laban.vn/ajax/find?type=1&query=$1"  \
            -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' \
            --compressed |
    jq      -r '.enViData.best.details' |
    tail    -n +10 |
    w3m     -dump -T text/html 
`"
