#!/usr/bin/env bash
# opener
# https://github.com/dylanaraps/fff/issues/101

[[ -z $1 || ! -e $1 ]] &&
    exit 1

mime="$(file -bIL "$1")"

case "$mime" in
    text/*|*/xml)
        "${VISUAL:-${EDITOR:-vi}}" "$1"
    ;;

    image/*)
        kitty icat "$1"
    ;;

    # video/*)
    #     mpv "$1"
    # ;;

    # audio/*)
    #     mpv "$1"
    # ;;

    # application/pdf*)
    #     open "$1"
    # ;;

    # *opendocument*|*openxmlformats*)
    #     open "$1"
    # ;;

    *)
        mpv "$1"
        # printf '%s\n' "warn: No program defined for $mime"
    ;;
esac
