#!/bin/bash

INP="$1"

FILENAME="$(BASENAME -- "$INP")"
EXTENSION="${FILENAME##*.}"
BASENAME="${FILENAME%.*}"

OUT="./$BASENAME.mp4"
echo "Converting $INP -> $OUT"

ffmpeg -f gif -i "$INP" \
   -pix_fmt yuv420p \
   -c:v libx264 \
   -movflags +faststart \
   -filter:v crop='floor(in_w/2)*2:floor(in_h/2)*2' \
   "$OUT"

 # * output mp4 is encoded with h264, support Firefox/Chrome/Safari in Windows, Mac OSX, Android, and iOS.
 # * one mp4 file for all platforms, there is no need to encode an extra `webm` movie, which encoding speed is pretty slow.
 # * format as `yuv420p` for Firefox compatibility, the downside is color becomes less-saturate than original gif.
 # * yuv420p only support even width/height, so crop filter is required
 # * `-movflags +faststart` flags are optimized for online view in browser
 # * compression ratio typically 10:1, pretty awesome. note that if original gif is < 512KB, convert as mp4 is less efficient.
