#!/bin/bash

giffile="$1"
webmfile="./$(basename $giffile .gif).webm"
echo "Converting $giffile -> $webmfile"

ffmpeg -i $giffile \
    -c:v libvpx-vp9 \
    -deadline realtime -cpu-used -8 \
    -crf 12 -b:v 500K \
    $webmfile
