#!/bin/bash

NOW=$(date +"%Y%m%d-%H%M%S")
MOV="/tmp/$1-$NOW.mov"
GIF="/tmp/$1-$NOW.gif"

ffcast -vv -w ffmpeg -f x11grab -show_region 1 -r 15 -s "%wx%h" -i ":0.0+%x,%y" $MOV && \
  ffmpeg-gif $MOV $GIF

