#!/bin/bash

URL="$1"

if [[ "$URL" == http://* || "$URL" == https://* ]]; then
    FMT=`youtube-dl -F "$URL" | fzf`

    if [[ -z $FMT ]]; then
        exit -1
    fi

    FMT=`echo "$FMT" | cut -d' ' -f1`
    
    /usr/local/bin/mpv --ytdl-format="$FMT" "$@"
else
    /usr/local/bin/mpv "$@"
fi
