#!/bin/bash

CID=~/.twitch_client_id

if [ ! -f "$CID" ]; then
    echo "$CID does not exist."
    exit -1
fi

URL=` \
    curl    -sS \
            -H 'Accept: application/vnd.twitchtv.v3+json' \
            -H "Client-ID: $(cat $CID)" \
            "https://api.twitch.tv/kraken/streams?limit=20&game=$1" |
    jq      -r '.streams[].channel | "\(.game)\t\(.status[0:96])\t\(.url)"' |
    column  -t -s $'\t' |
    fzf     --cycle --no-sort --reverse --tiebreak=index --no-multi --ansi |
    grep    -o 'https://.*' \
`
if [ -z "$URL" ]; then
    exit;
fi

mpv "$URL"
