#!/bin/bash

CID=~/.twitch_client_id

if [ ! -f "$CID" ]; then
    exit;
fi

CID=$(cat $CID)

if [ -z "$CID" ]; then
    exit;
fi

GID=`  curl    -sS -H "Client-ID: $CID" "https://api.twitch.tv/helix/games/top" |
        jq      -r '.data[] | "\(.id)\t\(.name)"'                               |
        column  -t -s $'\t'                                                     |
        fzf     --cycle --no-sort --reverse --tiebreak=index --no-multi --ansi  |
        awk     '{print $1}'
`

if [ -z "$GID" ]; then
    exit;
fi

URL=`   curl    -sS -H "Client-ID: $CID" "https://api.twitch.tv/helix/streams?limit=20&game_id=$GID" |
        jq      -r '.data[] | "\(.user_name)\t\(.title)"'                                            |
        column  -t -s $'\t'                                                                          |
        fzf     --cycle --no-sort --reverse --tiebreak=index --no-multi --ansi                       |
        awk     '{print $1}'
`

if [ -z "$URL" ]; then
    exit;
fi


URL="https://twitch.tv/$URL"

FMT=`youtube-dl -F "$URL" | fzf`

if [[ -z $FMT ]]; then
    exit -1
fi

FMT=`echo "$FMT" | cut -d' ' -f1`

mpv --ytdl-format="$FMT" "$URL"
