#!/bin/bash

if [ $1 == 'off' ]; then
  pkill xcompmgr &
elif [ $1 == 'on' ]; then
  xcompmgr -c -C -t-5 -l-5 -r4.2 -o.55 &
elif [ $1 == 'toggle' ]; then
  if pgrep -x "xcompmgr" > /dev/null; then
    pkill xcompmgr &
  else
    xcompmgr -c -C -t-5 -l-5 -r4.2 -o.55 &
  fi
fi

exit 0
