#! /bin/sh

# start sxhkd
pgrep sxhkd > /dev/null || sxhkd&

# start lemonbar
pkill -USR1 -x lemonbar
pkill -USR1 -x ~/.config/lemonbar/lemonbarrc
~/.config/lemonbar/lemonbarrc | lemonbar \
  -F "#fafafa" -B "#373b41" \
  -f "a14" &

# disable touchpad by default
~/.bin/touchpadctl disable

# start xflux
pgrep xflux > /dev/null || xflux -l 36 -g 128&

# disable caps lock
setxkbmap -option ctrl:nocaps

bspc monitor -d 1 2 3

bspc config border_width          1
bspc config window_gap            0

bspc config split_ratio           0.52
bspc config borderless_monocle    false
bspc config gapless_monocle       false
bspc config click_to_focus        true
bspc config initial_polarity      second_child
bspc config presel_feedback_color "#0e0e0e"

# prevent fullscreen
bspc subscribe node_state | while read msg mid did nid state value; do
  [ "$state $value" = "fullscreen on" ] || continue
  bspc node $nid -t tiled
done&
