#! /bin/sh

# start sxhkd
pgrep sxhkd > /dev/null || sxhkd&

# start urxvt deamon
pgrep urxvtd > /dev/null || urxvtd -q -f -o

# disable touchpad by default
~/.bin/touchpadctl disable

# start xflux
pgrep xflux > /dev/null || xflux -l 36 -g 128&

# disable caps lock
setxkbmap -option ctrl:nocaps

# set desktop background color
xsetroot -solid "#9e9e9e"

bspc monitor -d 1 2

bspc config border_width         1
bspc config window_gap           4
bspc config normal_border_color  "#373b41"
bspc config focused_border_color "#CC342B"

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config click_to_focus       true
