#! /bin/sh

# start sxhkd
pgrep sxhkd > /dev/null || sxhkd&

# start lemonbar
(killall lemonbarrc || true) && (killall lemonbar || true) && \
  ~/.config/lemonbar/lemonbarrc&

bspc monitor -d 1 2 3 4 5

bspc config border_width          1
bspc config window_gap            5

bspc config split_ratio           0.52
bspc config borderless_monocle    false
bspc config gapless_monocle       false
bspc config click_to_focus        true
bspc config initial_polarity      second_child

bspc config presel_feedback_color "#666666"
bspc config focused_border_color "#999999"
bspc config normal_border_color "#666666"
